### ISSUE TITLE
Manuscript: field changes

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#32]
As for the fields in `Manuscript`:
1. Add a new field `name` that will contain the name of the manuscript
1. Copy the _name_ information from the field `information` to the field `name`
1. Change the contents of the current field `information` to only contain information
    1. ANd make sure that it allows for `TagKeyword` (was: TagQnote) per issue #31

**Comment by ErwinKomen** [comment]
Actions:
1. Added new field `name`
1. Made a 'Data Migration' that moved the info from `information` into `name`
1. Added `TagKeyword` link to this `information` field

**Comment by PietroDelcorno** [comment]
Ok new section for information and the possibility to use keywords there

**Problem**: The visualization in “Sermon collection” now does not work properly (see for instance the collection “Quadragesimale virgilianum” (code 6). Instead of the “information” we need to have visualized the “Manuscript” (in this case: Assisi, Biblioteca del Sacro Convento, Fondo Antico, ms. 557, fol. 105r-138v), then the link (which might be only a yes/no info, with a *) and perhaps the indication whether there is something in the box “information” (again, not the content, by a yes/no indication, with a *). [On this, see also #36] 
So we have: Manuscript [text]; Link [yes/no]; Information [yes/no], which in this case would more or less result in: 
Assisi, Biblioteca del Sacro Convento, Fondo Antico, ms. 557, fol. 105r-138v ¦   *   ¦   *   ¦

**Comment by ErwinKomen** [comment]
The above pertains to the SermonCollection details view.
See issue #44
