### ISSUE TITLE
SermonCollection listview: layout

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#59]
Pietro (6):
> List of sermon collection, considering the space we have, it would be useful to indicate, beside the year of the first edition also the place of the first edition and perhaps the publisher?

**Comment by ErwinKomen** [comment]
Okay done.
Note: non-sortable.

**Comment by PietroDelcorno** [comment]
Two small things:
1) Instead of "... place", it is better "ed. place" or "city" (printed editions are always connected with a city, so we avoid the duplication of place"). As well, instead of "... publisher" it is fine just "publisher".
2) If it is not a problem, it would be useful to have also these as "sortable" - it would allow to see quickly which city 'produces' the first editions or which publisher is keen to print new collection.

**Comment by ErwinKomen** [comment]
Action on the two things:
1. That was easy!
1. This is not easy:
    1. Add a two new fields to the table called `firstediplace` and `firstedipubli`
    1. Adapt the method `adapt_editions` of `SermonCollection`
    1. Make a 'data-migration' to make sure that the new fields are filled in first-time
    1. Adapt `CollectionList` (in views.py) to show the correct firstediplace and firstedipubli (allowing sorting on them is not difficult!)

**Comment by ErwinKomen** [comment]
Okay, corrected.

**Comment by PietroDelcorno** [comment]
Perfect. Thank you
