### ISSUE TITLE
Edition: listview filters (a.k.a. 'Collections: consultation')

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#64]
Pietro (11):
> Issue of the consultation of the data about the paratextual elements in different collections (to think another time)

Erwin: please explain more detailed what the request here is.

**Comment by PietroDelcorno** [comment]
In https://lentensermons.cls.ru.nl/edition/list we have now only three filters (collection, author, place), plus the indication of the publisher and year of edition in the list. 
Yet, in the description of each edition (see for instance https://lentensermons.cls.ru.nl/edition/view/28/ ), many other data are stored, such as the format (this can be added as a filter), the number of folia and a series of information about the paratextual elements. 
We have to think how to make them available in a user friendly way. For instance, if one wants to know which edition has a dedicatory letter, which has images etc etc, it would be very useful to be able to ask to show a list of them, instead of having to go through each entry. 
So, if possible, about the paratextual elements, it would be usuful to have a system to say "show me the list of editions that have this feature".

**Comment by ErwinKomen** [comment]
I need to have this right. Are you asking for the following:
> Add the following filters to the **Edition listview**, where each filter is on text, and allows the use of wildcards:
> 1. **Format**, field `format`
> 1. **Folia**, field `folia`
> 1. **Number of sermons**, field `numsermons`
> 1. **Front page**, field `frontpage`
> 1. **Prologue**, field `prologue`
> 1. **Dedicatory letter**, field `dedicatory`
> 1. **Table of contents**, field `contents`
> 1. **List of sermons**, field `sermonlist`
> 1. **Other texts**, field `othertexts`
> 1. **Images**, field `images`
> 1. **Full title**, field `fulltitle`
> 1. **Colophon**, field `colophon`

**Comment by PietroDelcorno** [comment]
What do you mean with "boolean"? 
Is it like: yes/no and if yes show it?

**Comment by PietroDelcorno** [comment]
Hi Erwin, 
I described the different type of filter and which seems to me the different options (yet, please, let me know the different otions that you see feasible). 
I hope that the attached document results clear to you - otherwise, please ask me.

[Edition - filters.docx](https://github.com/ErwinKomen/RU-lenten/files/4913465/Edition.-.filters.docx)

**Comment by ErwinKomen** [comment]
> 
> 
> What do you mean with "boolean"?
> Is it like: yes/no and if yes show it? (Like in https://lentensermons.cls.ru.nl/collection/list with the filter "Has manuscript")

Exactly

**Comment by ErwinKomen** [comment]
Consultation of the document above leads to the following table with desires:

| Description | field name | field type | filter type |
|-----|-----|-----|-----|
| **Publishers** | `publishers` | m2m | text + select2 multi |
| **Year** | `date`, `date_late` | int | date range |
| **Format** | `format` | text | options (--, 2, 4, 8, 16) |
| **Number of Folia** | `folia` | text | text |
| **Number of sermons** | `numsermons` | text | text |
| **Front page** | `frontpage` | text | boolean |
| **Prologue** |  `prologue` | text | boolean |
| **Dedicatory letter** |  `dedicatory` | text | boolean |
| **Table of contents** |  `contents` | text | boolean |
| **List of sermons** |  `sermonlist` | text | boolean |
| **Other texts** |  `othertexts` | text | boolean |
| **Images** |  `images` | text | boolean |
| **Full title** |  `fulltitle` | text | boolean |
| **Colophon** |  `colophon` | text | boolean |

**Comment by ErwinKomen** [comment]
Implementation notes:
1. Added daterange processing to the basic listview filtering
