### ISSUE TITLE
Sermon listview: add filter on several fields

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#80]
(Spin-off from issue #15)
> start with the most important **fields**, which are those of the description of the “Sermon”, namely: “Main division”; “Summary” (and perhaps, also “General notes”?). 
> For what concerns **where to put** this searching tool, it can be an additional filter in the selected filters in sermon/list (we could call “division and summary”). 
>
> On the way to **visualize** the result, I am ready to hear your suggestions. It seems to me that we have at least two options: 1) do as it is now with keywords (where it is immediately visible the context where a word appears); 2) do as it is with the other filters of sermon/list, which show the simple list of sermons (then one would need to open and look in the summary/main division).

**Comment by ErwinKomen** [comment]
> Fictional example, the visualization of the search of the word "dog" would indicate:
Info of the sermon [code; author; collection; liturgical day; main topic]; dog [searched word]; summary [place - which can be indicated just with capital letters: MD = main division; S = summary; GN = general notes].

**Comment by ErwinKomen** [comment]
### Actions
1. Implement the "show or hide columns" (from Passim), since that is going to be helpful for this issue

**Comment by ErwinKomen** [comment]
### Usage notes
1. Make sure to do Ctrl + F5 (or the equivalent on Mac)
1. All listviews now have an additional button to the right of the Search button (top-right)
    1. Pressing this button reveals a row of buttons-per-column in the listview. Press these column buttons to hide or show columns.
1.

**Comment by PietroDelcorno** [comment]
1. Ok
2.
2. Ok. 
Just for sermon view, I suggest: 
a) to open automatically with the row of buttons-per-column visible (and the button serves to hide it). 
b) to open with disactivated the column "Division and summary" since it indicates (_unidentified_) which is a bit a cofusing message

So to have this: 
![image](https://user-images.githubusercontent.com/65396747/123065718-b4550200-d40f-11eb-9e72-82fe4b984889.png)

Instead of this:
![image](https://user-images.githubusercontent.com/65396747/123066159-16156c00-d410-11eb-9283-bee5c2a86a8a.png)

3. I understand the instruction but I still have some issue. 
Given that we are dealing with long texts, no one is going to search a "complete match" (i), which would mean - if I understand - to search for the whole text in a division or in a summary. 
I understand the function of the wildcards (ii), yet in this case - since it applies if I understand to a "complete match" - it does not work well; for instance, I cannot put now: peccat* (peccatum/peccatoris/peccatorum) or virgi* (Virgin/virginity). Wildcards in this case work well if we connect them with the option (iii).
The last option (iii) works well and is clear. If I understand, it allows also to search for several words together (e.g. for sermons that contain both gold# and quality#) and for a string (e.g. "his mother#"). If I saw correctly, this function can be connected with wildcards by putting first # and then * (so virgi#* allows to have _virgin_ and _virginalem_), am I right?
My question is: can make this specific search function the first option, which means if one write: gold quality - without # or " or * - instead of looking for a complete match the search is for the presence of these specific words in the division/summary? If not or time consuming, no problem (see my next comment).  

I think that below the search mask we need to put **a line with basic instruction**, saying: "Use # for search a specific word and * as wildcard. For instance: gold#, virgi#*" 

4. Ok. 
But in some cases it does not show the results, for instance if I look for Peter# the result is this: 

![image](https://user-images.githubusercontent.com/65396747/123073272-90e18580-d416-11eb-894a-45bd9c509a34.png)

The same for Judas# or Jew#*. 
Can be that the issue is with words that are labelled as keyword in the texts?

**Comment by ErwinKomen** [comment]
### Implementations

1. Ok (this was using Ctrl + F5).
2. Behaviour for all listview
    1. Special for Sermon listview: 
        1. autohide for division/summary - _ok, done_
        2. show buttons for column show/hide automatically on loading the page - _Ok, added basic_list feature `colwrap_show` _

**Comment by PietroDelcorno** [comment]
2.i.a. It still shows division/summary and hides _thema_ (I double check doing Crtl + F5)
2.i.b. OK

3. It works better and I think that 3.ii works well. Yet, some points are still not clear to me. I give some example with words with different wildcards of the number of their results:
Jews = 15 [correct] 
Jews# = 15 [correct]
Jew = 16 [correct: 15 Jews + 1 Jewish ]
Jew# = 0 [correct]
Jew* = 0 [wrong, I was expecting here 16 results...]
Jew#* = 16 [correct]
What for me is a bit confusing is the use of *, since it seems to work only in combination with #, while I was expecting that Jew* would provide the 16 results. 

A second aspect is the possibilities to search for more words contemporary. Again, a couple of examples:
gold sin = 0
gold# sin# = 1 
devil sin = 0
devil# sin# = 3 
Per se, it works, but we might have to alert the user by changing the message in the helptext (3.iii) - we can se which is the best message to provide once you explain to me (or changed) the function of # * . 

4. OK

**Comment by ErwinKomen** [comment]
2.i.a Solved

3. The way the wildcards work are described as: 
    `Use # to limit the search to one specific word and use * as a wildcard. For instance: gold#, virgi#*`
    This means:
        k = a

**Comment by PietroDelcorno** [comment]
2.i.a. is still the same, also if I use Ctrl+F5 - I tried also from another computer. It opens always in this format (see below). Of course, it is not a big issue, but remains a bit strange:

![image](https://user-images.githubusercontent.com/65396747/123930405-0063f180-d990-11eb-850b-562b30ff2de7.png)

3. Thanks, now it is more clear to me. I also introduce an entry in "Instruction" about it: "Search sermon (divisions and summaries)" - please, check if what I wrote there is correct. There is the problem that the asterisk * is a special symbol in markdown, so it was for me impossible to write there without spaces words like '*form*' and "natural*', since it is interpreted by the computer as the request to put sections of the texts in italics. Any solution for that? For the moment, I simply added a space, to let the asterisk visible...

4. Search of more then one word. I understand what you say about devil# and sin#.
Still, I need to understand how the mechanism works properly, i.e. if we can allow people to look for the occurrence of two words simultaneously in a text, which might be quite useful. 
Now I see that one can search for two consecutive words, i.e. 'Natural gold' (this is already good to know...).
If I specify the words with the # now I have: 'natural# gold #' same result of 'natural gold' (I think it is correct) and that 'natural dust' is different from 'natural# dust#' (which is again correct, since we do not have "natural dust" but a sermon in which the two terms occurs in the summary in two distinct point). Yet, as you pointed out, the order of the words is influential in this case, so if I look at 'dust# natural#' the result is different from 'natural# dust#' (0 against 1). 
My question is:
Is it possible (without too much work) to unify the results, which means to make the results independent from the order in which the terms occur in an entry (so that there is no difference in looking either for 'natural# dust#' or to 'dust# natural#')? 
If not, no problem. The solution is just to advise the users suggesting them that to search two terms they need to do it twice (i.e. to search both for 'natural# dust#' and to 'dust# natural#',

5. Acronyms - small change.
In the column division/summary, please change MD in MD-T (i.e. Main division - Translation) and MD-L in MD-O (Main division - Original... although it is almost always Latin, this is more correct)

**Comment by ErwinKomen** [comment]
2.i.a This is kind of weird. I got the wrong page on the website. My code in the development environment gave me the correct result. I then checked whether all files on the server were up to date -- they were. Then I re-started the server application, and it came up correctly:
![image](https://user-images.githubusercontent.com/11887269/125250112-2e352880-e2f6-11eb-8e76-4ca54a98b362.png)

**Comment by PietroDelcorno** [comment]
Perfect with everything.
In particular, great if you solved the issue on 4 about unifying the results for looking either for 'natural# dust#' or for 'dust# natural#'. Perfect that it works only for this search tool (it is not needed in the others) and I will update the instructions to mention also this feature. 
Still, now there are problems with instruction that I/we wrote: "The use of only the * means that the research is no longer word based, the whole text (division, summary) must start with that term, which may be followed by anything else. For instance, searching for 'natural*' you will find the summary of a sermon starting with the worlds: Natural gold..." 
Now if I search natural*, the following message appears: 
 
![image](https://user-images.githubusercontent.com/65396747/125289402-7c125680-e31f-11eb-94ae-34584b3a410d.png)

It is not a problem, since I don't see the need to look only and specifically at the beginning of my summaries - for instance, now one can look at ' natural gold' and find the right entry without troubles. 
Perhaps, the easiest thin to do is to change the instruction description, so to clarify to use * only as a specification after # (in case, let me know). 
Yet perhaps it is the sign of some problem you might look at.

**Comment by ErwinKomen** [comment]
Resolved that error.
